export const HomeFeaturedItems = [
  {
    name: 'Adidas Pureboost',
    image: 'https://utfs.io/f/vp3TJw7SgFuVLvFC29Xt8J0m2ykQ9bjZcFLzrONgCVaWIShG',
    url: '/sneakers',
    brand: 'Asics',
    height: '1000',
    width: '1200',
    tags: 'ABCDE',
  },
  {
    name: 'Brooks Superstream 12 Ultra Compete',
    image:
      'https://3kkrq3j76r.ufs.sh/f/vp3TJw7SgFuVW5gAlKhS9HPZNgGLbKi58kEFVhw2m1ptO37T',
    brand: 'Brooks',
    height: '1000',
    width: '1200',
    url: '/sneakers#radix-:Rafnjcq:-trigger-new_arrivals',
    tags: 'Runner',
  },
  {
    name: 'Nike All Weather Trainer XI',
    image: 'https://utfs.io/f/vp3TJw7SgFuVoSe2iTdRUg0ah3tD6yMACBjfiZnkdJYzL8c5',
    brand: 'Asics',
    height: '1000',
    width: '1200',
    url: '/sneakers',
    tags: 'Trainer',
  },
  {
    name: 'Shop Mens',
    image: 'https://utfs.io/f/vp3TJw7SgFuVKh3S9cBmRUvSPJ3z5BiOsYaxw7e20CNTbQht',
    brand: '',
    height: '1000',
    width: '1200',
    url: '/mens',
    tags: 'Runner',
  },
  // {
  //   name: 'Shop Womens',
  //   image: 'https://utfs.io/f/vp3TJw7SgFuVSBJGrzf3sMprD0z14mwIJ5TRZet3kXxQdyCu',
  //   brand: '',
  //   height: '1000',
  //   width: '1200',
  //   url: '/womens',
  //   tags: 'xzczxuchxz',
  // },
  {
    name: 'Shop Womens',
    image: 'https://utfs.io/f/vp3TJw7SgFuVLC5t5ESXt8J0m2ykQ9bjZcFLzrONgCVaWISh',
    brand: '',
    height: '1000',
    width: '1200',
    url: '/womens',
    tags: 'Runner',
  },
  // {
  //   name: 'Shop Mens',
  //   image: 'https://utfs.io/f/vp3TJw7SgFuVomeqTJdRUg0ah3tD6yMACBjfiZnkdJYzL8c5',
  //   brand: '',
  //   height: '1000',
  //   width: '1200',
  //   url: '/mens',
  //   tags: 'xzczxuchxz',
  // },
  // {
  //   name: 'Shop Womens',
  //   image: 'https://utfs.io/f/vp3TJw7SgFuVsbP8ynQvGHMF95opXgVAqD7ticOUj16IxvP3',
  //   brand: '',
  //   height: '1000',
  //   width: '1200',
  //   url: '/womens',
  //   tags: 'xzczxuchxz',
  // },
];
